apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsheeter-deployment
  labels:
    app: tsheeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tsheeter
  template:
    metadata:
      labels:
        app: tsheeter
    spec:
      containers:
      - name: tsheeter
        image: dgoeke/tsheeter:0.0.1
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        envFrom:
        - secretRef:
            name: tsheeter
